ADD: Modeling
wecode-bootcamp-korea/22-2nd-Metgo-backend pull request #1
Opened 2021-07-20 11:20 UTC by tycode4

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 초기 모델링
	 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-07-20 11:46 UTC, lordmyshepherd requested changes

2021-07-20 11:46 UTC, lordmyshepherd commented on metGo/settings.py
> +    'applications',
주석은 지워주세요~

2021-07-20 11:46 UTC, lordmyshepherd commented on masters/models.py
> +    service       = ManyToManyField('services.Service', through='services.MasterService', related_name='masters')
`master.services`로 객체 속성에 접근할 수 있도록 복수형으로 만들어주세요!
```suggestion
    services       = ManyToManyField('services.Service', through='services.MasterService', related_name='masters')
```

2021-07-20 11:46 UTC, lordmyshepherd commented on quotations/models.py
> +    application_master = ForeignKey('ApplicationMaster', on_delete='CASCADE')
제대로 동작 하나요?
아래와 같이 수정해야되지 않나요?
```suggestion
    application_master = ForeignKey('ApplicationMaster', on_delete=models.CASCADE)
```

2021-07-20 11:46 UTC, lordmyshepherd commented on reviews/models.py
> +    rating  = IntegerField()
`rating`은 `PositiveInterField()`를 사용해주세요~
왜 그럴까요?

2021-07-20 11:46 UTC, lordmyshepherd commented on services/models.py
> +    master   = ManyToManyField('masters.Master', through='MasterService', related_name='services')
마찬가지로 `masters`로 복수로 만들어주세요.

2021-07-20 11:46 UTC, lordmyshepherd commented on users/models.py
> +class User(TimeStampModel):
초이스 필드를 사용한 이유가 뭔가요?

2021-07-20 12:20 UTC, tycode4 commented on quotations/models.py
> +    application_master = ForeignKey('ApplicationMaster', on_delete='CASCADE')
죄송합니다! 수정 중입니다!

2021-07-20 12:20 UTC, tycode4 commented on reviews/models.py
> +    rating  = IntegerField()
넵! 수정하겠습니다!

2021-07-20 12:21 UTC, tycode4 commented on masters/models.py
> +    service       = ManyToManyField('services.Service', through='services.MasterService', related_name='masters')
수정하겠습니다!

2021-07-20 12:21 UTC, tycode4 commented on metGo/settings.py
> +    'applications',
네! 지우겠습니다!

2021-07-20 12:35 UTC, tycode4 commented on services/models.py
> +    master   = ManyToManyField('masters.Master', through='MasterService', related_name='services')
넵 수정했습니다!

2021-07-20 12:39 UTC, tycode4 commented on users/models.py
> +class User(TimeStampModel):
male, female만 받으려고 사용했습니다만.. 새로운 도전입니다!

2021-07-20 12:43 UTC, tycode4 commented
수정 완료했습니다!

2021-07-20 16:24 UTC, tycode4 commented
여러번의 실험을 통해 commit들을 합쳐 보냅니다..

2021-07-20 21:59 UTC, lordmyshepherd requested changes

2021-07-20 21:59 UTC, lordmyshepherd commented on applications/models.py
> +    gender_choice = (
새로운 시도 👍

Django에에서 choice field를 사용하실거면, Enum으로 관리할 수 있도록 아래와 같은 형태로 만들어주시는게 좋습니다.
==
![image](https://user-images.githubusercontent.com/53214510/126400753-fb66ebfc-5216-4112-8807-e21087b76489.png)

2021-07-20 21:59 UTC, lordmyshepherd commented on applications/models.py
> +    gender_choice = (
공식문서 참고
https://docs.djangoproject.com/en/3.2/ref/models/fields/#enumeration-types

2021-07-21 02:08 UTC, tycode4 commented on applications/models.py
> +    gender_choice = (
감사합니다! 참고해서 수정해보았습니다!

2021-07-21 02:36 UTC, lordmyshepherd commented on applications/models.py
> +    gender_choice = (
수정이 안된 것 같습니다!

2021-07-21 04:08 UTC, Jay9393 commented on applications/models.py
> +    gender_choice = (
병민님! 말씀해주신 django 공식문서에 나와있는 enum 으로 관리를 하는것이 아래 사진과 같은게 맞을까요??
그러면 gender column 에서는 male 은 1 female 은 2로 관리하면 되는건가요??
<img width="531" alt="Screen Shot 2021-07-21 at 1 00 07 PM" src="https://user-images.githubusercontent.com/80879214/126428824-42a32b0f-abdf-4635-826b-75812dfd1eac.png">

<img width="1004" alt="Screen Shot 2021-07-21 at 1 07 23 PM" src="https://user-images.githubusercontent.com/80879214/126429428-2651d204-574f-4fe3-aa6c-1b9452df6253.png">

2021-07-21 06:15 UTC, lordmyshepherd commented on applications/models.py
> +    gender_choice = (
👍  맞습니다~~ 
하지만 이경우는 Interger Choice 보다는 textchoices로 만드는게 좋지 않을까요?
그래야 gender에 male female로 저장될 것 같아요!

2021-07-21 06:45 UTC, Jay9393 commented on applications/models.py
> +    gender_choice = (
감사합니다! 바로 수정해서 pr 올리겠습니다~!~!

2021-07-21 10:08 UTC, lordmyshepherd commented
LGTM 👍

2021-07-21 10:08 UTC, merged