ADD: master detail profile page
wecode-bootcamp-korea/22-2nd-Metgo-backend pull request #10
Opened 2021-07-26 01:55 UTC by tycode4

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 고수 상세페이지
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-07-26 01:55 UTC, tycode4 commented
![image](https://user-images.githubusercontent.com/81765028/126922872-9dbbbf39-9108-4a8e-8cb4-2ed898f192ac.png)

2021-07-26 12:08 UTC, Kang-kyunghun requested changes

2021-07-26 12:08 UTC, Kang-kyunghun commented on masters/urls.py
> +    path('/profile/<int:master_id>', MasterProfileDetailView.as_view())
```suggestion
    path('/<int:master_id>', MasterProfileDetailView.as_view())
```

2021-07-26 12:08 UTC, Kang-kyunghun commented on masters/views.py
> +class MasterProfileDetailView(View):
```suggestion
class MasterView(View):
```

2021-07-26 12:08 UTC, Kang-kyunghun commented on masters/views.py
> +            master    = Master.objects.get(id=master_id)
if와 exists()을 활용해서 존재 유무 판단해 주세요.

2021-07-26 12:08 UTC, Kang-kyunghun commented on masters/views.py
> +            quotation = Quotation.objects.filter(master_id=master.id)
master을 통해서 데이터를 가져와 보세요.

2021-07-26 12:08 UTC, Kang-kyunghun commented on masters/views.py
> +                    'rating'         : (round(review.aggregate(average=Avg('rating'))['average'], 1) if review.exists() else 0.0),
위에서 선언해서 가져오는 것이 더 가독성이 좋을 것 같습니다.

2021-07-26 12:08 UTC, Kang-kyunghun commented on masters/views.py
> +                    'region'         : master.region.name,
구두로 전해드린대로 제거해 주세요.

2021-07-27 01:53 UTC, tycode4 commented on masters/urls.py
> +    path('/profile/<int:master_id>', MasterProfileDetailView.as_view())
수정했습니다!

2021-07-27 01:53 UTC, tycode4 commented on masters/views.py
> +class MasterProfileDetailView(View):
수정했습니다!

2021-07-27 01:54 UTC, tycode4 commented on masters/views.py
> +            master    = Master.objects.get(id=master_id)
if not exists로 수정했습니다!

2021-07-27 01:54 UTC, tycode4 commented on masters/views.py
> +            quotation = Quotation.objects.filter(master_id=master.id)
역참조 하여 불러오는 방식으로 수정했습니다!

2021-07-27 01:54 UTC, tycode4 commented on masters/views.py
> +                    'rating'         : (round(review.aggregate(average=Avg('rating'))['average'], 1) if review.exists() else 0.0),
rating을 따로 위로 뺐습니다!

2021-07-27 01:55 UTC, tycode4 commented on masters/views.py
> +                    'region'         : master.region.name,
넵 제거 했습니다!

2021-07-29 11:13 UTC, lordmyshepherd commented
컨플릭트 해결해주세요~

2021-07-29 12:20 UTC, Kang-kyunghun commented
LGTM~!!

2021-07-29 12:20 UTC, merged