ADD: SigninView and Kakao Login API
wecode-bootcamp-korea/22-2nd-Metgo-backend pull request #11
Opened 2021-07-26 12:23 UTC by showmethr23

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 일반 로그인 API
- 카카오 로그인 API
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-07-26 12:23 UTC, showmethr23 commented
통신하고 리뷰 수정하고 유닛테스트도 얼른 해보겠습니다 (_ _)

2021-07-27 01:10 UTC, Kang-kyunghun requested changes

2021-07-27 01:10 UTC, Kang-kyunghun commented on users/views.py
> +            )
get_or_create 사용 할 때는 pk 같은 유일한 값으로 판단 후 만약 생성 되었을 때 추가 정보를 입력해 주어야 합니다.

2021-07-27 01:10 UTC, Kang-kyunghun commented on users/views.py
> +            user  = User.objects.get(kakao_id = kakao_id)
get_or_create의 사용법 숙지가 아직 덜 되어 있는 것 같아 예시코드 남기지 않았습니다. 다시 한 번 찾아보고, 저한테 따로 질문해 주세요.

2021-07-29 09:21 UTC, Kang-kyunghun commented
LGTM~~!!

2021-07-29 09:21 UTC, merged