Add: ApplicationView
wecode-bootcamp-korea/22-2nd-Metgo-backend pull request #13
Opened 2021-07-28 03:07 UTC by Jay9393

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-07-28 04:02 UTC, Jay9393 commented
요청서 뷰 통신 화면입니다.
![application- post](https://user-images.githubusercontent.com/80879214/127261576-8f29362b-06f7-444d-8432-cc8d47b33dbe.png)

고수 매칭 뷰 통신화면입니다
![mastermatching - get ](https://user-images.githubusercontent.com/80879214/127261579-10d3b819-2704-4ae6-9b14-077982431c81.png)

2021-07-28 05:24 UTC, Kang-kyunghun commented
PR template 제대로 작성해 주세요.

2021-07-28 10:47 UTC, Jay9393 commented
PR 메세지 수정 완료 하였습니다! 코드도 말씀하신대로 수정 하고 Unit test 까지 확인 했습니다~

2021-07-29 02:44 UTC, Kang-kyunghun requested changes

2021-07-29 02:44 UTC, Kang-kyunghun commented on applications/views.py
> +            return JsonResponse({'message' : 'Does not matching masters'}, status = 404)
1. filter 결과의 존재 유무를 판단 할 때는 .exists()을 활용해 주는 것이 좋습니다. 해당 method는 정말 존재 유무만 판단하기 때문에 모든 데이터를 가져오지 않습니다. 따라서 더 효율적입니다.
2. 그런데 지금 view 같은 경우는 메칭된 master가 없을 경우 error보다는 그냥 없는 그대로, 즉 빈 list([])가 반환 되는 것이 더 적절합니다. 따라서 해당 예외처리는 제거해 주세요.

2021-07-29 02:44 UTC, Kang-kyunghun commented on applications/views.py
> +        reviews          = Review.objects.select_related('master')
for문 안에 있는 maser로부터 데이터를 가져와 보세요.

2021-07-29 02:44 UTC, Kang-kyunghun commented on applications/views.py
> +                q  &= Q(birth__lte = birth)
```suggestion
        if age:
            today = datetime.date.today()
            birth = today - relativedelta(year = today.year-age)
            q_age = Q(birth__range = (birth-relativedelta(year= birth.year-10), birth))
            q &= q_age if age != 50 else Q(birth__lte = birth)
```
코드 한번 줄여 봤는데, 한 번 참고해 보세요.

2021-07-29 09:28 UTC, Jay9393 commented on applications/views.py
> +            return JsonResponse({'message' : 'Does not matching masters'}, status = 404)
수정 완료하였습니다~!

2021-07-29 09:28 UTC, Jay9393 commented on applications/views.py
> +        reviews          = Review.objects.select_related('master')
수정 완료하였습니다~!

2021-07-29 09:28 UTC, Jay9393 commented
conflict 해결 완료 했습니다~!

2021-07-29 10:02 UTC, Kang-kyunghun commented
LGTM~~!!

2021-07-29 10:03 UTC, merged