Add: Service View
wecode-bootcamp-korea/22-2nd-Metgo-backend pull request #3
Opened 2021-07-21 12:11 UTC by Jay9393

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-07-21 12:16 UTC, Jay9393 commented
해당 메인 화면의 view 입니다.
<img width="1250" alt="Screen Shot 2021-07-21 at 9 14 24 PM" src="https://user-images.githubusercontent.com/80879214/126486739-b2e722dc-4235-4490-8931-10462c33762a.png">


![https://s3-us-west-2.amazonaws.com/secure.notion-static.com/97e36ad5-491b-4845-a771-d2859e49f3bc/Screen_Shot_2021-07-21_at_2.46.04_PM.png](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/97e36ad5-491b-4845-a771-d2859e49f3bc/Screen_Shot_2021-07-21_at_2.46.04_PM.png)

2021-07-22 01:02 UTC, Kang-kyunghun commented on metGo/urls.py
> +    path('<str:category_name>', MainView.as_view())
카테고리 id를 안 받고 이름으로 받는 이유가 있나요?

2021-07-22 01:02 UTC, Kang-kyunghun commented on services/views.py
> +class MainView(View):
페이지가 아닌 어떤 자원을 활용하는지 나타나게 View class 이름을 지어 주세요.

2021-07-22 01:12 UTC, Jay9393 commented on metGo/urls.py
> +    path('<str:category_name>', MainView.as_view())
페이지 상단에 레슨, 홈/리빙 등 카테고리 부분이 하드코딩으로 이루어져있어서 이름으로 받았습니다! 해당부분에도 저희 카테고리 데이터를 뿌려주고 id 로 받는게 나을까요??

2021-07-22 01:12 UTC, Jay9393 commented on services/views.py
> +class MainView(View):
넵 바로 수정하겠습니다~!

2021-07-22 03:46 UTC, Jay9393 commented on metGo/urls.py
> +    path('<str:category_name>', MainView.as_view())
수정 완료하였습니다~!

2021-07-22 03:46 UTC, Jay9393 commented on services/views.py
> +class MainView(View):
수정 완료하였습니다~!

2021-07-22 03:47 UTC, Jay9393 commented
Category View 를 나눠서 작성 할까 고민하다가 ServiceView 안에 Category list 를 담아서 주는 방법으로 수정했습니다

2021-07-22 06:51 UTC, Jay9393 commented on services/views.py
> +class MainView(View):
수정 완료하였습니다.

2021-07-22 08:08 UTC, Jay9393 commented
ServiceDetailView 통신 결과입니다.
<img width="379" alt="Screen Shot 2021-07-22 at 4 59 26 PM" src="https://user-images.githubusercontent.com/80879214/126607843-19a40ba5-bcb4-4b92-8eae-5845e50fb83e.png">

2021-07-23 05:59 UTC, Kang-kyunghun commented
오전에 구두로 말씀드리데로 수정 부탁드립니다.

2021-07-26 10:08 UTC, Kang-kyunghun requested changes

2021-07-26 10:08 UTC, Kang-kyunghun commented on services/views.py
> +        service = Service.objects.get(id=service_id)
if와 exists()을 활요해서 존재 유무 판단해 주세요.

2021-07-26 12:14 UTC, Jay9393 commented
경훈님 service_id를 갖는 service의 존재유무를 판단하라는 말씀이시죠???

2021-07-27 01:06 UTC, Kang-kyunghun commented
> 경훈님 service_id를 갖는 service의 존재유무를 판단하라는 말씀이시죠???

네 맞습니다~!!

2021-07-27 01:37 UTC, Jay9393 commented
구두로 말씀해주신 부분까지 전부 수정 완료하였고 unit test 추가해서 다시 push 하겠습니다~

2021-07-27 07:55 UTC, Jay9393 commented
Unit test 완료 하였습니다 ~!

2021-07-27 09:23 UTC, Kang-kyunghun commented
LGTM~~!! 👍

2021-07-27 09:23 UTC, merged