ADD: Signup View
wecode-bootcamp-korea/22-2nd-Metgo-backend pull request #4
Opened 2021-07-21 15:51 UTC by showmethr23

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입 view 작성

## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-07-22 01:03 UTC, Kang-kyunghun requested changes

2021-07-22 01:03 UTC, Kang-kyunghun commented on users/views.py
> +                return JsonResponse({"message":"VALIDATION_ERROR"}, status=401)
```suggestion
            data = json.loads(request.body)
            
            if not User.validate(data):
                return JsonResponse({"message":"VALIDATION_ERROR"}, status=401)
```

2021-07-22 01:03 UTC, Kang-kyunghun commented on users/views.py
> +            hashed_password = bcrypt.hashpw(password.encode("utf-8"), bcrypt.gensalt())
=을 기준으로 정렬해 주세요.

2021-07-22 01:03 UTC, Kang-kyunghun commented on users/views.py
> +                birth = birth
=을 기준으로 정렬해 주세요.

2021-07-22 03:46 UTC, showmethr23 commented on users/views.py
> +                return JsonResponse({"message":"VALIDATION_ERROR"}, status=401)
수정했습니다!

2021-07-22 03:46 UTC, showmethr23 commented on users/views.py
> +            hashed_password = bcrypt.hashpw(password.encode("utf-8"), bcrypt.gensalt())
수정했습니다!

2021-07-22 03:47 UTC, showmethr23 commented on users/views.py
> +                birth = birth
수정했습니다!

2021-07-23 01:23 UTC, Kang-kyunghun requested changes

2021-07-23 01:23 UTC, Kang-kyunghun commented on masters/views.py
> +from django.http import JsonResponse
import 기준으로 정렬해 주세요.

2021-07-23 01:23 UTC, Kang-kyunghun commented on masters/views.py
> +            )
```suggestion
            password        = data["password"]
            hashed_password = bcrypt.hashpw(password.encode("utf-8"), bcrypt.gensalt())

            Master.objects.create(
                name         = data['name'],
                password     = hashed_password.decode(),
                phone        = data['phone'],
                gender       = data['gender'],
                email        = data['email'],
                birth        = data['birth'],
                region       = data['region'],
                main_service = data['main_service'],
                career       = data['career'],
            )
```
여러번 사용되는 값들이 아니니까 다음과 같이 바꾸는 것이 가독성이 더 좋을 것 같습니다.

2021-07-23 01:23 UTC, Kang-kyunghun commented on users/views.py
> +            )
위의 리뷰와 마찬가지 입니다. 위의 리뷰 참고해서 수정해 주세요.

2021-07-23 01:32 UTC, showmethr23 commented on masters/views.py
> +from django.http import JsonResponse
수정 했습니다!

2021-07-23 01:32 UTC, showmethr23 commented on masters/views.py
> +            )
수정 했습니다!

2021-07-23 01:32 UTC, showmethr23 commented on users/views.py
> +            )
수정 했습니다!

2021-07-23 01:33 UTC, showmethr23 commented
일단 수정 된거 올리고 유닛 테스트 후 추가 해서 올리겠습니다 (_ _)

2021-07-28 05:07 UTC, Kang-kyunghun commented
유닛테스트 안 올라 온 것 같은데 확인해 주세요.

2021-07-28 10:59 UTC, showmethr23 commented
유닛 테스트 올렸습니다 (_ _)

2021-07-29 02:04 UTC, Kang-kyunghun commented
LGTM~~!!

2021-07-29 02:04 UTC, merged