ADD: users' reviews in master's profile
wecode-bootcamp-korea/22-2nd-Metgo-backend pull request #9
Opened 2021-07-26 01:53 UTC by tycode4

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 고수 상세페이지에 해당 고수의 고객 리뷰
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-07-26 01:54 UTC, tycode4 commented
![image](https://user-images.githubusercontent.com/81765028/126922808-8985d8c5-b476-4686-bf6e-f17f7e09412c.png)

2021-07-26 10:10 UTC, Kang-kyunghun requested changes

2021-07-26 10:10 UTC, Kang-kyunghun commented on reviews/views.py
> +            master     = Master.objects.get(id=master_id)
if와 exisrs()을 활용해서 존재 유무 판단해 주세요.

2021-07-26 10:10 UTC, Kang-kyunghun commented on reviews/views.py
> +            reviews    = Review.objects.filter(master_id=master.id)
master로부터 review을 가져와 보세요.

2021-07-26 10:10 UTC, Kang-kyunghun commented on reviews/views.py
> +                    'rating'     : review.rating if Review.objects.filter(aster_id=master.id).exists() else 0.0,
```suggestion
                    'rating'     : review.rating,
```

2021-07-26 10:10 UTC, Kang-kyunghun commented on reviews/views.py
> +            return JsonResponse({'results':results, 'total_pages':len(review_list)}, status=200)
total_page의 값을 어떻게 가져와야 할지 생각해 보세요.

2021-07-26 10:10 UTC, Kang-kyunghun commented on reviews/views.py
> +m
오타 같은데 제거해 주세요.

2021-07-26 12:18 UTC, tycode4 commented on reviews/views.py
> +            master     = Master.objects.get(id=master_id)
넵 알겠습니다!

2021-07-27 02:00 UTC, tycode4 commented on reviews/views.py
> +            reviews    = Review.objects.filter(master_id=master.id)
역참조해서 수정했습니다!

2021-07-27 02:00 UTC, tycode4 commented on reviews/views.py
> +                    'rating'     : review.rating if Review.objects.filter(aster_id=master.id).exists() else 0.0,
제거 했습니다!

2021-07-27 02:00 UTC, tycode4 commented on reviews/views.py
> +            return JsonResponse({'results':results, 'total_pages':len(review_list)}, status=200)
page_range를 써서 총 페이지수를 구했습니다!

2021-07-27 02:00 UTC, tycode4 commented on reviews/views.py
> +m
오타 제거했습니다!

2021-07-27 02:02 UTC, Kang-kyunghun commented
수정하고 PR 안 올리신 것 같은데 확인 부탁드립니다.

2021-07-27 02:06 UTC, tycode4 commented
확인해보겠습니다!

2021-07-27 02:11 UTC, tycode4 commented
PR올렸습니다!

2021-07-29 12:23 UTC, lordmyshepherd requested changes

2021-07-29 12:23 UTC, lordmyshepherd commented on services/migrations/0001_initial.py
> +=======
컨플릭트 수정 안된 파일이 너무 많네요!!

2021-07-29 12:23 UTC, lordmyshepherd commented on users/migrations/0001_initial.py
> +=======
컨플릭트 수정 안된 파일이 너무 많네요!!

2021-07-29 12:23 UTC, lordmyshepherd commented on quotations/migrations/0001_initial.py
> +=======
컨플릭트 수정 안된 파일이 너무 많네요!!

2021-07-29 12:23 UTC, lordmyshepherd commented on quotations/migrations/0001_initial.py
> +>>>>>>> 3c73968 (ADD: tests.py)
컨플릭트 수정 안된 파일이 너무 많네요!!

2021-07-29 12:26 UTC, tycode4 commented on users/migrations/0001_initial.py
> +=======
엇 죄송합니다! 바로 수정하겠습니다!

2021-07-29 12:26 UTC, tycode4 commented on quotations/migrations/0001_initial.py
> +=======
바로 수정하겠습니다!

2021-07-29 12:26 UTC, tycode4 commented on quotations/migrations/0001_initial.py
> +>>>>>>> 3c73968 (ADD: tests.py)
바로 수정하겠습니다!

2021-07-29 12:38 UTC, Kang-kyunghun commented
LGTM~!

2021-07-29 12:39 UTC, merged